spring:
  application:
    name: mdm-person-conversion-api
  rabbitmq:
    host: ${MDM_QUEUEMGR_HOST}
    port: ${MDM_QUEUEMGR_PORT}
    username: ${MDM_QUEUEMGR_USERNAME}
    password: ${MDM_QUEUEMGR_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

server:
  port: 8082
